import React,{useState} from 'react';
import {frequencies} from './audio-engine';
const labels=['60','170','350','1k','3.5k','10k'];
export default function Effects({effects,setEffects,globalEq,setGlobalEq,hasSong,onSave}){
 const [scope,setScope]=useState('song');const local=scope==='song';const eq=local?(effects.eq??globalEq):globalEq;
 const enabled=!local||!!effects.eq;
 const update=(i,v)=>{const a=[...eq];a[i]=Math.round(Math.max(-12,Math.min(12,v))*2)/2;local?setEffects({...effects,eq:a}):setGlobalEq(a)};
 const point=(event,i)=>{const rect=event.currentTarget.ownerSVGElement.getBoundingClientRect();update(i,12-((event.clientY-rect.top)/rect.height*240-20)/200*24)};
 return <section className="effects-panel"><div className="effects-heading"><h2>Sound</h2><button className="outline" disabled={!hasSong} onClick={onSave}>Save as version</button></div><div className="effect-sliders"><label>Tempo <b>{Math.round(effects.tempo*100)}%</b><input aria-label="Tempo" disabled={!hasSong} type="range" min=".5" max="1.5" step=".01" value={effects.tempo} onChange={e=>setEffects({...effects,tempo:+e.target.value})}/></label><label>Pitch <b>{effects.pitch>0?'+':''}{effects.pitch.toFixed(1)} semitones</b><input aria-label="Pitch" disabled={!hasSong} type="range" min="-12" max="12" step=".1" value={effects.pitch} onChange={e=>setEffects({...effects,pitch:+e.target.value})}/></label></div><div className="eq-tabs"><button className={local?'selected':''} onClick={()=>setScope('song')}>This song</button><button className={!local?'selected':''} onClick={()=>setScope('global')}>Global EQ</button>{local&&<label><input type="checkbox" checked={!!effects.eq} disabled={!hasSong} onChange={e=>setEffects({...effects,eq:e.target.checked?[...globalEq]:null})}/>Override global EQ</label>}</div><div className={`eq-graph ${!enabled?'inherited':''}`}><svg viewBox="0 0 600 240" preserveAspectRatio="none" role="img" aria-label="Equalizer gain graph"><line x1="35" x2="565" y1="120" y2="120" stroke="#63715a"/>{[20,70,170,220].map(y=><line key={y} x1="35" x2="565" y1={y} y2={y} stroke="#313931"/>)}<polyline fill="none" stroke="#d4f465" strokeWidth="2" points={eq.map((v,i)=>`${50+i*100},${120-v/12*100}`).join(' ')}/>{eq.map((v,i)=><circle key={i} cx={50+i*100} cy={120-v/12*100} r="8" fill="#d4f465" style={{cursor:enabled?'ns-resize':'default',touchAction:'none'}} onPointerDown={e=>{if(enabled){e.currentTarget.setPointerCapture(e.pointerId);point(e,i)}}} onPointerMove={e=>{if(enabled&&e.buttons)point(e,i)}}/>)}</svg></div><div className="eq-bands">{frequencies.map((f,i)=><label key={f}>{labels[i]} Hz<input aria-label={`${local?'Song':'Global'} EQ ${f} Hz gain`} type="number" min="-12" max="12" step=".5" disabled={!enabled||local&&!hasSong} value={eq[i]} onChange={e=>update(i,+e.target.value)}/><small>dB</small></label>)}</div><div className="effects-foot"><span>{local?(effects.eq?'Song EQ replaces global EQ.':'Using global EQ.'):'Global EQ is remembered on this device.'} Unsaved song changes reset when you switch tracks.</span><button className="subtle" onClick={()=>local?setEffects({tempo:1,pitch:0,eq:null}):setGlobalEq(frequencies.map(()=>0))}>Reset {local?'song':'global EQ'}</button></div></section>
}
